#!/bin/sh

if command -v i3 &>/dev/null;
then
  dropbox start &>/dev/null
fi

# Causes issues in Linux +Man, Man page exited with code 127
if command -v apt &>/dev/null;
then 
	export MANPAGER='vim +Man!'
  nvidia-settings -a '[gpu:0]/GPUFanControlState=1' &> /dev/null
  nvidia-settings -a '[fan]/GPUTargetFanSpeed=50' &> /dev/null
fi

if command -v apt &>/dev/null && (pgrep tmux &>/dev/null && ! pgrep dropbox &>/dev/null);
then
  tmux rename-window running-dropbox &>/dev/null
  dropbox start &>/dev/null
else
  echo -e "No need to start dropbox" 
fi
