#!/bin/sh

# Changes pager to use in nvim
# NOTE: nvim will be used if vim has been symlinked to nvim


# Environment variables set everywhere
export EDITOR="vim"
export TERMINAL="alacritty"
export BROWSER="brave"

# XDF CONIG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# zsh config dir
export ZDOTDIR=$HOME/.config/zsh

HISTFILE="$XDG_DATA_HOME"/zsh/history/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000


# for zsh viins to work jj 'vi-cmd-mode'
export KEYTIMEOUT=15

export NVIM_DOTFILES="$XDG_CONFIG_HOME/nvim"

export STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/config.toml

# helps TMUX display proper LS dircolors when -G flag is passed
# Values can be:
# tmux-256color
# xterm-256color 
# screen-256color
# NOTE: xterm-256color can screw TMUX {ls -G} 
export TERM=xterm-256color

export MANWIDTH=999

# ############## OS Specifics ####################

# Causes issues in Linux +Man, Man page exited with code 127
if ! command -v apt > /dev/null; then 
	export MANPAGER='vim +Man!'
  nvidia-settings -a '[gpu:0]/GPUFanControlState=1'
  nvidia-settings -a '[fan]/GPUTargetFanSpeed=50'
fi
