#!/bin/sh

UNAME_OUT="$(uname -s)"

case "${UNAME_OUT}" in
  Linux*)

    if command -v i3 &>/dev/null;
    then
      dropbox start &>/dev/null
    fi

    export MANPAGER='vim +Man!'
    nvidia-settings -a '[gpu:0]/GPUFanControlState=1' &> /dev/null
    nvidia-settings -a '[fan]/GPUTargetFanSpeed=50' &> /dev/null

    if pgrep tmux &>/dev/null && ! pgrep dropbox &>/dev/null;
    then
      tmux rename-window running-dropbox &>/dev/null
      dropbox start &>/dev/null
    else
      echo -e "No need to start dropbox" 
    fi

    # Adds  brew /bin to path
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    ;;
esac
