#!/usr/bin/env bash

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

compare_float() {
  if [ ${1%.*} -eq ${2%.*} ] && [ ${1#*.} \> ${2#*.} ] || [ ${1%.*} -gt ${2%.*} ]; then
    echo ">"
  else
    echo "<="
  fi
}

set_tmux_env() {
    local -n tmux_session_env_REF="$1"

    for env_var in "${!tmux_session_env_REF[@]}";
    do
        tmux setenv -g "$env_var" "${tmux_session_env_REF[$env_var]}"
    done
}

declare -A tmux_session_env

tmux_session_env[FZF_TMUX_BIN]="${CURRENT_DIR}/.fzf-tmux"

# Healthy checks
tmux_version=$(tmux -V | grep -oE '[0-9]+\.[0-9]*')
if [ $(compare_float $tmux_version "3.1") == ">" ]; then
  tmux_session_env[TMUX_FZF_OPTIONS]="-p -w 40% -h 38% -m"
else
  tmux_session_env[TMUX_FZF_OPTIONS]="-m"
fi

set_tmux_env tmux_session_env
