#!/usr/bin/env bash

FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --header='Select window to switch'"

window_selected=$(tmux list-windows | eval "$FZF_TMUX_BIN $TMUX_FZF_OPTIONS" | awk -F':' '{print $1}')

[[ -z $window_selected ]] && exit

tmux display-message "$window_selected"

tmux select-window -t "$window_selected"
