# Environment variables set everywhere
export EDITOR="vim"
export TERMINAL="alacritty"
export BROWSER="brave"

 # XDF CONIG
 export XDG_CONFIG_HOME=$HOME/.config
 export XDG_CACHE_HOME=$HOME/.cache
 export XDG_DATA_HOME=$HOME/.local/share

 # zsh config dir
 export ZDOTDIR=$HOME/.config/zsh
