#!/bin/sh

# Changes pager to use in nvim
# NOTE: nvim will be used if vim has been symlinked to nvim
export MANPAGER='vim +Man!'
export MANWIDTH=999

# for zsh viins to work jj 'vi-cmd-mode'
export KEYTIMEOUT=15

export DOTFILES="$XDG_CONFIG_HOME/nvim"

export STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/config.toml

# helps TMUX display proper LS dircolors when -G flag is passed
# Values can be:
# tmux-256color
# xterm-256color 
# screen-256color
# NOTE: xterm-256color can screw TMUX {ls -G} 
export TERM=xterm-256color
